# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
 - task: PublishBuildArtifacts@1
      inputs:
        artifactName: drop
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '/home/vsts/work/1/s/target/sparkjava-hello-world-1.0.war'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '/home/vsts/mvnwar.zip'
    replaceExistingArchive: true
    verbose: true
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'current'
    itemPattern: '**/*.war **/*.zip'
    targetPath: '$(Pipeline.Workspace)'