steps:
 - name: maven:3-jdk-8
   entrypoint: mvn
   args: ['package','-Dmaven.test.skip=true']

artifacts:
  objects:
    location: 'gs://preetcb/'
    paths: ['/workspace/target/sparkjava-hello-world-1.0.war', 'cloudbuild.yaml']
