steps:
 - name: maven:3-jdk-8
   entrypoint: mvn
   args: ['package','-Dmaven.test.skip=true']
 - name: scrpt
   args: ['pwd']
artifacts:
  objects:
    location: 'gs://preetcb/'
    paths: ['cloudbuild.yaml']
